#pragma once

#define MAKE_C_VERSION(X,Y) V ## X ## _ ## Y
#define LIBSAT_VERSION_SYM \
    MAKE_C_VERSION(@LIBSAT_VERSION_MAJOR@, @LIBSAT_VERSION_MINOR@)

#define LIBSAT_VERSION_STRING \
"@LIBSAT_VERSION_MAJOR@.@LIBSAT_VERSION_MINOR@.@LIBSAT_VERSION_REL@"
